# Generated by Django 4.1.4 on 2022-12-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_response', models.JSONField(default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.message')),
            ],
        ),
    ]
