# Generated by Django 4.1.4 on 2022-12-14 17:48

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[core.validators.validate_campaign_settings]),
        ),
    ]
